import { useMemo, useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, Award, BarChart3, CalendarDays, Mail, MapPin, Search, Send, Trophy, Users, Video } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SAMPLE_CANDIDATES } from '../data/marketplaceSamples';

type Stage = 'Mission assigned' | 'Assessment review' | 'Interview ready' | 'Interview scheduled' | 'Final review';
type Candidate = (typeof SAMPLE_CANDIDATES)[number] & { stage: Stage; mission: string; completion: number; correctness: number; contribution: number; score: number; interviewAt?: string };
const stages: Stage[] = ['Mission assigned', 'Assessment review', 'Interview ready', 'Interview scheduled', 'Final review'];
const MISSIONS: Record<string, string> = {
  'Frontend Engineer': 'Accessible performance dashboard', 'Product Designer': 'Checkout usability redesign', 'Data Analyst': 'Conversion drop investigation',
  'Backend Engineer': 'Resilient notification API', 'Growth Marketer': 'Zero-budget launch strategy', 'UX Researcher': 'Activation research synthesis',
  'Project Manager': 'Cross-team delivery recovery', 'DevOps Engineer': 'Zero-downtime deployment plan',
};
const initialCandidates: Candidate[] = SAMPLE_CANDIDATES.slice(0, 64).map((candidate, index) => {
  const correctness = 52 + (index * 11) % 47;
  const contribution = 48 + (index * 13) % 50;
  const completion = index % 7 === 0 ? 65 : 100;
  const score = Math.round(correctness * .5 + contribution * .3 + completion * .2);
  return { ...candidate, correctness, contribution, completion, score, mission: MISSIONS[candidate.title] || `${candidate.title} role challenge`, stage: score >= 80 ? 'Interview ready' : score >= 65 ? 'Assessment review' : 'Mission assigned' };
});

export default function EmployerInterviewCenter() {
  const [candidates, setCandidates] = useState(initialCandidates);
  const [view, setView] = useState<'assessment' | 'interview'>('assessment');
  const [role, setRole] = useState('All roles');
  const [query, setQuery] = useState('');
  const [selectedId, setSelectedId] = useState(initialCandidates[0].id);
  const [message, setMessage] = useState('');
  const [messages, setMessages] = useState<Record<string, string[]>>({});
  const roles = ['All roles', ...new Set(candidates.map((candidate) => candidate.title))];
  const filtered = useMemo(() => candidates.filter((candidate) => (role === 'All roles' || candidate.title === role) && `${candidate.name} ${candidate.title} ${candidate.mission}`.toLowerCase().includes(query.toLowerCase())), [candidates, query, role]);
  const interviewCandidates = filtered.filter((candidate) => candidate.score >= 75 || ['Interview scheduled', 'Final review'].includes(candidate.stage));
  const selected = candidates.find((candidate) => candidate.id === selectedId) || interviewCandidates[0];
  const average = Math.round(filtered.reduce((sum, candidate) => sum + candidate.score, 0) / Math.max(filtered.length, 1));
  const update = (id: string, patch: Partial<Candidate>) => setCandidates((current) => current.map((candidate) => candidate.id === id ? { ...candidate, ...patch } : candidate));
  const send = () => { if (!selected || !message.trim()) return; setMessages((current) => ({ ...current, [selected.id]: [...(current[selected.id] || []), message.trim()] })); setMessage(''); };

  return <main className="product-page -mx-4 min-h-[calc(100vh-4rem)] px-4 py-7 sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8"><div className="product-shell max-w-[1500px]">
    <Link to="/employer" className="product-button-secondary"><ArrowLeft className="h-4 w-4" />Back to dashboard</Link>
    <header className="mt-6 border-b border-slate-200 pb-7"><p className="product-eyebrow">Evidence-first candidate selection</p><h1 className="product-title mt-3 text-4xl font-black">Assessment & Interview Center</h1><p className="product-copy mt-2 max-w-4xl">Candidates first complete a role-specific mission or challenge. Review verified results, compare potential and correctness, then advance the strongest evidence to structured interviews.</p></header>
    <section className="mt-6 overflow-hidden rounded-2xl bg-[#12213a] p-5 text-white"><div className="grid gap-2 md:grid-cols-4">{[['1','Role mission','Employer assigns practical work'],['2','Evidence scoring','Correctness and contribution'],['3','Qualified shortlist','Potential reviewed by team'],['4','Structured interview','Selected candidates advance']].map(([number,title,detail], index) => <div key={title} className="relative flex items-center gap-3 rounded-xl bg-white/5 p-4"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full font-black ${index < 2 ? 'bg-[#b7ff3c] text-[#12213a]' : 'bg-white/10 text-white'}`}>{number}</span><span><strong className="block text-sm">{title}</strong><small className="text-slate-400">{detail}</small></span>{index < 3 && <ArrowRight className="absolute -right-3 z-10 hidden h-5 w-5 text-[#b7ff3c] md:block" />}</div>)}</div></section>
    <section className="mt-5 grid gap-3 sm:grid-cols-4"><Metric icon={<Users />} value={filtered.length} label="Candidates assessed" /><Metric icon={<BarChart3 />} value={`${average}%`} label="Average challenge score" /><Metric icon={<Award />} value={filtered.filter((candidate) => candidate.score >= 80).length} label="High-potential results" /><Metric icon={<Video />} value={candidates.filter((candidate) => ['Interview scheduled','Final review'].includes(candidate.stage)).length} label="Interview pipeline" /></section>
    <section className="product-surface mt-5 p-5"><div className="grid gap-3 md:grid-cols-[1fr_18rem]"><label className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search candidate, role, or mission" className="min-h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm font-semibold outline-none" /></label><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold">{roles.map((item) => <option key={item}>{item}</option>)}</select></div><div className="mt-4 flex gap-2 overflow-x-auto">{roles.slice(1).map((item) => <button key={item} onClick={() => setRole(item)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-black ${role === item ? 'bg-[#173b67] text-white' : 'bg-slate-100 text-slate-600'}`}>{item} · {candidates.filter((candidate) => candidate.title === item).length}</button>)}</div></section>
    <div className="mt-5 inline-flex rounded-xl border border-slate-200 bg-white p-1 shadow-sm"><button onClick={() => setView('assessment')} className={`rounded-lg px-4 py-2.5 text-sm font-black ${view === 'assessment' ? 'bg-[#173b67] text-white' : 'text-slate-500'}`}><Trophy className="mr-2 inline h-4 w-4" />Mission results</button><button onClick={() => setView('interview')} className={`rounded-lg px-4 py-2.5 text-sm font-black ${view === 'interview' ? 'bg-[#173b67] text-white' : 'text-slate-500'}`}><Video className="mr-2 inline h-4 w-4" />Qualified interviews · {interviewCandidates.length}</button></div>
    {view === 'assessment' ? <AssessmentResults candidates={filtered} onAdvance={(candidate) => { update(candidate.id, { stage: 'Interview ready' }); setSelectedId(candidate.id); setView('interview'); }} /> : <InterviewWorkspace candidates={interviewCandidates} selected={selected} setSelectedId={setSelectedId} update={update} messages={messages} message={message} setMessage={setMessage} send={send} />}
  </div></main>;
}

function AssessmentResults({ candidates, onAdvance }: { candidates: Candidate[]; onAdvance: (candidate: Candidate) => void }) {
  const ranked = [...candidates].sort((a,b) => b.score - a.score);
  return <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_1.35fr]"><section className="product-surface p-6"><div className="flex justify-between"><div><p className="product-eyebrow">Results chart</p><h2 className="mt-2 text-xl font-black">Candidate potential</h2></div><BarChart3 className="h-5 w-5 text-[#173b67]" /></div><div className="mt-7 space-y-4">{ranked.slice(0,10).map((candidate, index) => <div key={candidate.id}><div className="mb-1.5 flex justify-between text-xs font-bold"><span>{index + 1}. {candidate.name}</span><strong>{candidate.score}%</strong></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${candidate.score >= 80 ? 'bg-[#b7ff3c]' : candidate.score >= 65 ? 'bg-[#173b67]' : 'bg-[#f3a6be]'}`} style={{ width: `${candidate.score}%` }} /></div></div>)}</div><div className="mt-6 flex flex-wrap gap-3 text-xs font-bold text-slate-500"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#b7ff3c]" />80+ Interview ready</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#173b67]" />65–79 Review</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#f3a6be]" />Below 65 Developing</span></div></section>
  <section className="product-surface overflow-hidden"><div className="border-b border-slate-100 p-5"><p className="product-eyebrow">Role challenge leaderboard</p><h2 className="mt-2 text-xl font-black">Evidence breakdown</h2></div><div className="max-h-[650px] divide-y divide-slate-100 overflow-y-auto">{ranked.map((candidate, index) => <article key={candidate.id} className="p-5"><div className="flex gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-xs font-black">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-black">{candidate.name}</h3><p className="text-xs font-bold text-[#173b67]">{candidate.title} · {candidate.mission}</p></div><strong className="text-2xl text-[#173b67]">{candidate.score}%</strong></div><div className="mt-4 grid grid-cols-3 gap-2"><Score label="Correctness" value={candidate.correctness} /><Score label="Contribution" value={candidate.contribution} /><Score label="Completion" value={candidate.completion} /></div><div className="mt-4 flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-[.65rem] font-black ${candidate.score >= 80 ? 'bg-lime-50 text-green-700' : candidate.score >= 65 ? 'bg-blue-50 text-[#173b67]' : 'bg-pink-50 text-pink-700'}`}>{candidate.score >= 80 ? 'High potential' : candidate.score >= 65 ? 'Needs review' : 'More evidence needed'}</span>{candidate.score >= 75 && <button onClick={() => onAdvance(candidate)} className="text-xs font-black text-[#173b67]">Advance to interview <ArrowRight className="inline h-3.5 w-3.5" /></button>}</div></div></div></article>)}</div></section></div>;
}

function InterviewWorkspace({ candidates, selected, setSelectedId, update, messages, message, setMessage, send }: { candidates: Candidate[]; selected?: Candidate; setSelectedId: (id: string) => void; update: (id: string, patch: Partial<Candidate>) => void; messages: Record<string,string[]>; message: string; setMessage: (value:string) => void; send: () => void }) {
  return <div className="mt-5 grid min-h-[650px] gap-5 lg:grid-cols-[minmax(22rem,.8fr)_minmax(30rem,1.2fr)]"><section className="product-surface overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-black">Qualified candidate queue</h2><p className="text-xs font-bold text-slate-500">{candidates.length} candidates advanced from role challenges</p></div><div className="max-h-[720px] divide-y divide-slate-100 overflow-y-auto">{candidates.map((candidate) => <button key={candidate.id} onClick={() => setSelectedId(candidate.id)} className={`flex w-full gap-3 p-4 text-left ${selected?.id === candidate.id ? 'bg-[#fcf0f5]' : 'hover:bg-slate-50'}`}><Avatar candidate={candidate} /><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{candidate.name}</strong><small className="block truncate font-bold text-slate-500">{candidate.title}</small><span className="mt-2 inline-flex rounded-full bg-white px-2 py-1 text-[.65rem] font-black text-[#173b67] ring-1 ring-slate-200">{candidate.stage}</span></span><strong className="text-[#173b67]">{candidate.score}%</strong></button>)}</div></section>
  {selected && <section className="product-surface flex flex-col overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="flex flex-wrap gap-4"><Avatar candidate={selected} /><div className="flex-1"><h2 className="text-xl font-black">{selected.name}</h2><p className="font-bold text-[#173b67]">{selected.title}</p><p className="mt-1 text-xs text-slate-500"><MapPin className="mr-1 inline h-3.5 w-3.5" />{selected.location} · Challenge {selected.score}%</p></div><Link to={`/employer/candidates/${selected.id}`} className="product-button-secondary text-xs">Full profile</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-black text-slate-500">INTERVIEW STAGE<select value={selected.stage} onChange={(event) => update(selected.id, { stage: event.target.value as Stage })} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold">{stages.slice(2).map((stage) => <option key={stage}>{stage}</option>)}</select></label><label className="text-xs font-black text-slate-500">DATE & TIME<input type="datetime-local" value={selected.interviewAt || ''} onChange={(event) => update(selected.id, { interviewAt: event.target.value, stage: 'Interview scheduled' })} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm font-bold" /></label></div></div><div className="flex-1 bg-slate-50 p-5"><div className="max-w-[85%] rounded-2xl bg-white p-4 text-sm leading-6 shadow-sm"><strong className="block">{selected.name}</strong>I completed the {selected.mission} challenge and I’m available to discuss my decisions.</div>{(messages[selected.id] || []).map((text,index) => <div key={index} className="ml-auto mt-4 max-w-[85%] rounded-2xl bg-[#173b67] p-4 text-sm text-white">{text}</div>)}</div><div className="border-t border-slate-100 p-4"><div className="mb-3 flex gap-2"><button onClick={() => setMessage(`Your ${selected.mission} result demonstrated strong potential. We would like to invite you to an interview.`)} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold"><CalendarDays className="mr-1 inline h-3.5 w-3.5" />Interview invitation</button><button onClick={() => setMessage('Please explain one key tradeoff you made during the role challenge.')} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold"><Mail className="mr-1 inline h-3.5 w-3.5" />Discuss result</button></div><div className="flex gap-2"><textarea value={message} onChange={(event) => setMessage(event.target.value)} className="min-h-12 flex-1 resize-none rounded-xl border border-slate-200 p-3 text-sm" placeholder="Message candidate…" /><button onClick={send} className="product-button-primary px-4"><Send className="h-4 w-4" /></button></div></div></section>}</div>;
}
function Score({ label, value }: { label:string; value:number }) { return <div className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between text-[.65rem] font-bold text-slate-500"><span>{label}</span><strong>{value}%</strong></div><div className="mt-2 h-1.5 rounded bg-slate-200"><div className="h-full rounded bg-[#173b67]" style={{ width:`${value}%` }} /></div></div>; }
function Avatar({ candidate }: { candidate:Candidate }) { return <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#173b67] text-xs font-black text-white">{candidate.name.split(' ').map((part) => part[0]).slice(0,2).join('')}</span>; }
function Metric({ icon,value,label }: { icon:ReactNode; value:string|number; label:string }) { return <article className="product-surface flex items-center gap-4 p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf2f7] text-[#173b67] [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><strong className="text-2xl font-black">{value}</strong><p className="text-xs font-bold text-slate-500">{label}</p></div></article>; }
