import { ArrowLeft, BadgeCheck, BarChart3, Briefcase, Mail, MapPin, MessageSquare, Star, Users } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { SAMPLE_CANDIDATES } from '../data/marketplaceSamples';

export default function EmployerCandidateProfile() {
  const { id } = useParams();
  const candidate = SAMPLE_CANDIDATES.find((item) => item.id === id);
  if (!candidate) return <div className="product-page py-16 text-center"><h1 className="text-2xl font-black">Candidate not found</h1><Link to="/employer/candidates" className="mt-4 inline-flex text-[#173b67]">Back to candidates</Link></div>;
  const signals = [
    { label: 'Role alignment', value: candidate.matchScore },
    { label: 'Skills evidence', value: 72 + candidate.id.length % 22 },
    { label: 'Collaboration', value: 68 + candidate.name.length % 26 },
    { label: 'Career verification', value: 76 + candidate.skills.length * 4 },
  ];
  return <div className="product-page -mx-4 min-h-[calc(100vh-4rem)] px-4 py-7 sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8"><div className="product-shell max-w-6xl">
    <Link to="/employer/candidates" className="product-button-secondary"><ArrowLeft className="h-4 w-4" />Back to candidate directory</Link>
    <section className="relative mt-6 overflow-hidden rounded-[2rem] bg-[#12213a] p-6 text-white sm:p-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-[#f7c8d9]/20 blur-3xl" /><div className="relative flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-5"><span className="flex h-24 w-24 items-center justify-center rounded-full border-4 border-white/20 bg-[#173b67] text-2xl font-black">{candidate.name.split(' ').map((part) => part[0]).join('')}</span><div><p className="text-xs font-black uppercase tracking-[0.12em] text-[#b7ff3c]">Verified candidate profile</p><h1 className="mt-2 text-3xl font-black">{candidate.name}</h1><p className="mt-1 font-bold text-slate-300">{candidate.title}</p><p className="mt-2 flex items-center gap-1.5 text-sm text-slate-400"><MapPin className="h-4 w-4" />{candidate.location}</p></div></div><div className="flex gap-3"><Link to="/messages" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-black text-[#173b67]"><MessageSquare className="h-4 w-4" />Message</Link><button className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#b7ff3c] px-4 text-sm font-black text-[#12213a]"><Star className="h-4 w-4" />Shortlist</button></div></div></section>
    <section className="mt-5 grid gap-3 sm:grid-cols-4">{signals.map((signal) => <article key={signal.label} className="product-surface p-5"><p className="text-2xl font-black text-[#173b67]">{signal.value}%</p><p className="mt-1 text-xs font-bold text-slate-500">{signal.label}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#b7ff3c]" style={{ width: `${signal.value}%` }} /></div></article>)}</section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]"><main className="space-y-6"><section className="product-surface p-6"><p className="product-eyebrow">Professional summary</p><h2 className="mt-3 text-xl font-black">Evidence-led {candidate.title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{candidate.name} is a {candidate.title.toLowerCase()} with visible project evidence across {candidate.skills.join(', ')}. Their profile demonstrates practical delivery, collaboration, and continuous learning.</p></section><section className="product-surface p-6"><div className="flex items-center gap-3"><BarChart3 className="h-5 w-5 text-[#173b67]" /><h2 className="text-xl font-black">Capability analysis</h2></div><div className="mt-6 space-y-5">{candidate.skills.map((skill, index) => { const value = Math.min(96, candidate.matchScore - 8 + index * 6); return <div key={skill}><div className="flex justify-between text-sm font-bold"><span>{skill}</span><span>{value}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#173b67]" style={{ width: `${value}%` }} /></div></div>; })}</div></section><section className="product-surface p-6"><div className="flex items-center gap-3"><Briefcase className="h-5 w-5 text-[#173b67]" /><h2 className="text-xl font-black">Experience evidence</h2></div><div className="mt-5 space-y-4">{['Delivered a measurable product improvement with a cross-functional team.', 'Created documented project evidence reviewed by JobX peers.', 'Contributed to open collaboration and received positive feedback.'].map((text, index) => <div key={text} className="flex gap-3 rounded-xl bg-slate-50 p-4"><BadgeCheck className="h-5 w-5 shrink-0 text-[#173b67]" /><div><strong className="text-sm">Verified outcome {index + 1}</strong><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div></div>)}</div></section></main><aside className="space-y-5"><section className="product-surface p-5"><h2 className="font-black">Candidate details</h2><div className="mt-4 space-y-4 text-sm text-slate-600"><p className="flex items-center gap-3"><Mail className="h-4 w-4 text-[#173b67]" />Contact through JobX</p><p className="flex items-center gap-3"><Users className="h-4 w-4 text-[#173b67]" />Open to collaboration</p><p className="flex items-center gap-3"><BadgeCheck className="h-4 w-4 text-[#173b67]" />Identity verified</p></div></section><section className="rounded-2xl bg-[#fcf0f5] p-5"><h2 className="font-black">Recruiter note</h2><p className="mt-2 text-sm leading-6 text-slate-600">Strong fit for roles requiring {candidate.skills.slice(0, 2).join(' and ')}. Consider a structured interview focused on delivery evidence.</p></section></aside></div>
  </div></div>;
}
