import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, Folder, MapPin, Search, Star, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SAMPLE_CANDIDATES } from '../data/marketplaceSamples';

export default function EmployerCandidates() {
  const [role, setRole] = useState('All roles');
  const [query, setQuery] = useState('');
  const roles = ['All roles', ...new Set(SAMPLE_CANDIDATES.map((candidate) => candidate.title))];
  const candidates = useMemo(() => SAMPLE_CANDIDATES.filter((candidate) => (role === 'All roles' || candidate.title === role) && `${candidate.name} ${candidate.location} ${candidate.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [query, role]);
  const averageMatch = Math.round(candidates.reduce((sum, candidate) => sum + candidate.matchScore, 0) / Math.max(1, candidates.length));
  return <div className="product-page -mx-4 min-h-[calc(100vh-4rem)] px-4 py-7 sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8"><div className="product-shell max-w-7xl">
    <Link to="/employer" className="product-button-secondary"><ArrowLeft className="h-4 w-4" />Back to dashboard</Link>
    <header className="mt-6 border-b border-slate-200 pb-7"><p className="product-eyebrow">Applicant database</p><h1 className="product-title mt-4 text-4xl font-black">Candidate folders</h1><p className="product-copy mt-3">Every candidate who applied is stored in a role folder. Search the full database, compare hiring signals, and open complete profiles.</p></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-3"><Metric icon={<Users />} value={candidates.length} label="Candidates in view" /><Metric icon={<BarChart3 />} value={`${averageMatch}%`} label="Average profile match" /><Metric icon={<Folder />} value={roles.length - 1} label="Role categories" /></section>
    <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-slate-900">Role folders</h2><button onClick={() => setRole('All roles')} className="text-xs font-black text-[#173b67]">View all applicants</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{roles.slice(1).map((item) => { const count = SAMPLE_CANDIDATES.filter((candidate) => candidate.title === item).length; return <button key={item} onClick={() => setRole(item)} className={`product-surface flex items-center gap-3 p-4 text-left ${role === item ? 'ring-2 ring-[#173b67]' : ''}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fcf0f5] text-[#173b67]"><Folder className="h-5 w-5" /></span><span className="min-w-0"><strong className="block truncate text-sm text-slate-900">{item}</strong><small className="text-slate-500">{count} applicants</small></span></button>; })}</div></section>
    <section className="product-surface mt-6 p-5"><div className="grid gap-3 sm:grid-cols-[1fr_16rem]"><label className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search this database by candidate, skill, or location" className="min-h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm font-semibold outline-none" /></label><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold">{roles.map((item) => <option key={item}>{item}</option>)}</select></div></section>
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{candidates.map((candidate) => <Link key={candidate.id} to={`/employer/candidates/${candidate.id}`} className="product-surface product-card-interactive p-5"><div className="flex items-start gap-3"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#173b67] text-sm font-black text-white">{candidate.name.split(' ').map((part) => part[0]).join('')}</span><div className="min-w-0 flex-1"><h2 className="truncate font-black text-slate-900">{candidate.name}</h2><p className="mt-0.5 truncate text-xs font-bold text-slate-500">{candidate.title}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-400"><MapPin className="h-3 w-3" />{candidate.location}</p></div><strong className="text-lg text-[#173b67]">{candidate.matchScore}%</strong></div><div className="mt-4 flex flex-wrap gap-1.5">{candidate.skills.map((skill) => <span key={skill} className="rounded-md bg-[#edf2f7] px-2 py-1 text-[0.68rem] font-bold text-[#173b67]">{skill}</span>)}</div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><span className="inline-flex items-center gap-1 text-xs font-bold text-slate-500"><Star className="h-3.5 w-3.5 text-[#b7ff3c] fill-[#b7ff3c]" />Verified evidence</span><span className="text-xs font-black text-[#173b67]">Full profile <ArrowRight className="inline h-3.5 w-3.5" /></span></div></Link>)}</div>
  </div></div>;
}

function Metric({ icon, value, label }: { icon: ReactNode; value: string | number; label: string }) { return <article className="product-surface flex items-center gap-4 p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf2f7] text-[#173b67] [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><strong className="text-2xl font-black text-slate-950">{value}</strong><p className="text-xs font-bold text-slate-500">{label}</p></div></article>; }
