export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  type: 'Full-time' | 'Part-time' | 'Contract' | 'Internship';
  workplaceType: 'On-site' | 'Hybrid' | 'Remote';
  experience: 'Entry Level' | 'Mid Level' | 'Senior' | 'Executive';
  salary: string;
  salaryMin: number;
  salaryMax: number;
  salaryCurrency: string;
  salaryPeriod: 'year' | 'month' | 'hour';
  tags: string[];
  skillsRequired: string[];
  description: string;
  requirements: string[];
  responsibilities: string[];
  benefits: string[];
  companyOverview: string;
  companySize: string;
  companyIndustry: string;
  companyFounded: string;
  postedAt: string;
  postedDate: string; // ISO date for filtering
  logoInitials: string;
  logoColor: string;
  matchScore?: number; // 0-100
  easyApply: boolean;
  externalUrl?: string;
  applicants: number;
  recruiterName?: string;
  recruiterTitle?: string;
  promoted: boolean;
  activelyRecruiting: boolean;
  connectionsAtCompany?: number; // "3 connections work here"
}

const CORE_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior React Engineer",
    company: "TechFlow",
    location: "San Francisco, CA",
    type: "Full-time",
    workplaceType: "Hybrid",
    experience: "Senior",
    salary: "$140k – $170k",
    salaryMin: 140000,
    salaryMax: 170000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["React", "TypeScript", "Performance"],
    skillsRequired: ["React", "TypeScript", "GraphQL", "Node.js", "Performance Optimization", "Jest"],
    description: "We are seeking a Senior React Engineer to lead our frontend architecture and deliver high-performance user interfaces for our enterprise SaaS product. You'll own the component library and mentor junior developers.",
    requirements: ["5+ years React experience", "Deep knowledge of TypeScript", "Experience with performance profiling", "GraphQL API design experience", "Bachelor's degree in CS or equivalent"],
    responsibilities: ["Lead frontend architecture decisions and set technical direction", "Build and maintain reusable component libraries", "Optimize application performance and user experience", "Mentor junior developers and conduct code reviews", "Collaborate with product and design teams to ship features"],
    benefits: ["Health, dental, vision insurance", "401(k) with 4% match", "Unlimited PTO", "Home office stipend ($1,000)", "Annual learning budget ($3,000)"],
    companyOverview: "TechFlow is a fast-growing enterprise SaaS company building intelligent workflow automation tools. Founded in 2018, we serve over 2,000 enterprise customers across 40 countries with a mission to make work smarter and more efficient.",
    companySize: "501–1,000 employees",
    companyIndustry: "Computer Software",
    companyFounded: "2018",
    postedAt: "2 days ago",
    postedDate: "2024-05-28",
    logoInitials: "TF",
    logoColor: "bg-blue-600",
    matchScore: 92,
    easyApply: true,
    applicants: 23,
    recruiterName: "Jessica Park",
    recruiterTitle: "Technical Recruiter",
    promoted: false,
    activelyRecruiting: true,
    connectionsAtCompany: 2
  },
  {
    id: "2",
    title: "Product Designer",
    company: "StudioX",
    location: "Remote",
    type: "Full-time",
    workplaceType: "Remote",
    experience: "Mid Level",
    salary: "$110k – $130k",
    salaryMin: 110000,
    salaryMax: 130000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["Figma", "UI/UX", "Prototyping"],
    skillsRequired: ["Figma", "Design Systems", "User Research", "Prototyping", "HTML/CSS"],
    description: "Join our creative team to design intuitive and beautiful web experiences. You'll work closely with product and engineering to bring concepts to life in a fully remote environment.",
    requirements: ["3+ years product design experience", "Strong portfolio showcasing web apps", "Proficiency in Figma", "Experience with design systems"],
    responsibilities: ["Design end-to-end user flows and interactive prototypes", "Conduct user research and usability testing", "Maintain and evolve the product design system", "Collaborate with engineers on implementation details", "Present design rationale to stakeholders"],
    benefits: ["Fully remote async culture", "Health insurance (US) or stipend (intl)", "Co-working space allowance", "Annual design conference budget", "Flexible hours"],
    companyOverview: "StudioX is a design-driven product studio that creates delightful digital experiences. With a team of 150+ designers and engineers, we partner with leading brands to solve complex user challenges through thoughtful, research-informed design.",
    companySize: "51–200 employees",
    companyIndustry: "Design Services",
    companyFounded: "2016",
    postedAt: "4 hours ago",
    postedDate: "2024-05-30",
    logoInitials: "SX",
    logoColor: "bg-purple-600",
    matchScore: 78,
    easyApply: true,
    applicants: 8,
    recruiterName: "Maria Santos",
    recruiterTitle: "Talent Acquisition",
    promoted: true,
    activelyRecruiting: true,
    connectionsAtCompany: 0
  },
  {
    id: "3",
    title: "Backend Developer (Go)",
    company: "CloudSync",
    location: "New York, NY",
    type: "Full-time",
    workplaceType: "On-site",
    experience: "Mid Level",
    salary: "$130k – $160k",
    salaryMin: 130000,
    salaryMax: 160000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["Go", "Microservices", "AWS"],
    skillsRequired: ["Go", "AWS", "Kubernetes", "gRPC", "PostgreSQL", "Docker"],
    description: "CloudSync is looking for a strong Backend Developer to help scale our cloud synchronization infrastructure using Go and AWS. You'll work on high-throughput distributed systems.",
    requirements: ["3+ years backend experience", "Production experience with Go", "Knowledge of AWS services", "Experience with distributed systems"],
    responsibilities: ["Design and implement scalable backend services in Go", "Build and maintain REST and gRPC APIs", "Monitor and optimize system performance and reliability", "Write comprehensive unit and integration tests", "Participate in on-call rotation and incident response"],
    benefits: ["Competitive salary + equity", "NYC office with rooftop", "Catered lunches daily", "Gym membership", "Commuter benefits"],
    companyOverview: "CloudSync provides enterprise-grade cloud synchronization and backup solutions. Our platform handles petabytes of data for Fortune 500 companies, ensuring secure, reliable data management in an increasingly distributed world.",
    companySize: "1,001–5,000 employees",
    companyIndustry: "Cloud Computing",
    companyFounded: "2014",
    postedAt: "1 day ago",
    postedDate: "2024-05-29",
    logoInitials: "CS",
    logoColor: "bg-sky-500",
    matchScore: 65,
    easyApply: false,
    externalUrl: "https://cloudsync.com/careers/backend-go",
    applicants: 67,
    recruiterName: "David Kim",
    recruiterTitle: "Senior Recruiter",
    promoted: false,
    activelyRecruiting: true,
    connectionsAtCompany: 5
  },
  {
    id: "4",
    title: "Data Scientist",
    company: "MetricSpace",
    location: "Boston, MA",
    type: "Full-time",
    workplaceType: "Hybrid",
    experience: "Mid Level",
    salary: "$120k – $150k",
    salaryMin: 120000,
    salaryMax: 150000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["Python", "Machine Learning", "SQL"],
    skillsRequired: ["Python", "SQL", "Machine Learning", "Statistics", "TensorFlow", "Data Visualization"],
    description: "Help us derive actionable insights from massive datasets. You'll build predictive models that drive our core business strategy and work closely with cross-functional teams.",
    requirements: ["Master's in relevant field", "Strong Python & SQL", "Experience with scikit-learn", "Statistical modeling background"],
    responsibilities: ["Develop and deploy machine learning models for business analytics", "Analyze large datasets to identify trends and opportunities", "Build data pipelines and ETL workflows", "Communicate findings to non-technical stakeholders", "Stay current with emerging ML techniques and tools"],
    benefits: ["Health & wellness programs", "Stock options", "Relocation assistance", "Parental leave (6 months)", "Free parking"],
    companyOverview: "MetricSpace is a data analytics firm that transforms raw data into strategic business intelligence. Founded by MIT researchers, our team of data scientists and engineers helps companies make smarter, data-driven decisions.",
    companySize: "201–500 employees",
    companyIndustry: "Data Analytics",
    companyFounded: "2017",
    postedAt: "3 days ago",
    postedDate: "2024-05-27",
    logoInitials: "MS",
    logoColor: "bg-emerald-600",
    matchScore: 45,
    easyApply: true,
    applicants: 42,
    promoted: false,
    activelyRecruiting: false,
    connectionsAtCompany: 1
  },
  {
    id: "5",
    title: "Marketing Manager",
    company: "GrowthGen",
    location: "Remote",
    type: "Full-time",
    workplaceType: "Remote",
    experience: "Senior",
    salary: "$90k – $120k",
    salaryMin: 90000,
    salaryMax: 120000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["B2B", "SEO", "Content Strategy"],
    skillsRequired: ["B2B Marketing", "SEO", "Content Strategy", "Google Analytics", "HubSpot", "Copywriting"],
    description: "Lead our marketing initiatives and drive inbound growth through strategic SEO, content marketing, and targeted campaigns. You'll own the entire demand generation pipeline.",
    requirements: ["4+ years B2B marketing", "Proven track record of ROI", "Excellent written communication", "Experience with marketing automation tools"],
    responsibilities: ["Develop and execute comprehensive marketing strategies", "Manage content calendar and oversee content production", "Run paid acquisition campaigns across multiple channels", "Analyze campaign performance and optimize for ROI", "Build and nurture partnerships with industry influencers"],
    benefits: ["Remote-first culture", "Performance bonuses", "Professional development fund", "Flexible vacation policy", "Team retreats (quarterly)"],
    companyOverview: "GrowthGen is a B2B marketing platform that helps SaaS companies accelerate growth. Our suite of tools empowers marketing teams to attract, convert, and retain customers through data-driven strategies.",
    companySize: "51–200 employees",
    companyIndustry: "Marketing Tech",
    companyFounded: "2019",
    postedAt: "5 days ago",
    postedDate: "2024-05-25",
    logoInitials: "GG",
    logoColor: "bg-orange-500",
    matchScore: 30,
    easyApply: true,
    applicants: 156,
    recruiterName: "Amy Chen",
    recruiterTitle: "HR Manager",
    promoted: true,
    activelyRecruiting: true,
    connectionsAtCompany: 0
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "InfraCore",
    location: "Austin, TX",
    type: "Full-time",
    workplaceType: "On-site",
    experience: "Senior",
    salary: "$150k – $180k",
    salaryMin: 150000,
    salaryMax: 180000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["Kubernetes", "CI/CD", "Terraform"],
    skillsRequired: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Linux", "Python"],
    description: "Maintain and scale our Kubernetes clusters and build robust CI/CD pipelines to empower our engineering team. You'll be the backbone of our infrastructure.",
    requirements: ["Strong Kubernetes knowledge", "Experience with Terraform", "Scripting skills (Python/Bash)", "5+ years infrastructure experience"],
    responsibilities: ["Manage and scale Kubernetes clusters in production", "Design and implement CI/CD pipelines for microservices", "Automate infrastructure provisioning with Terraform", "Implement monitoring, alerting, and incident response procedures", "Collaborate with development teams on infrastructure needs"],
    benefits: ["Competitive base + annual bonus", "Stock options", "On-site gym and cafeteria", "Relocation package", "Conference attendance"],
    companyOverview: "InfraCore provides cloud infrastructure management solutions for enterprises running mission-critical workloads. Our platform simplifies container orchestration and infrastructure automation for engineering teams worldwide.",
    companySize: "1,001–5,000 employees",
    companyIndustry: "Infrastructure Software",
    companyFounded: "2015",
    postedAt: "1 week ago",
    postedDate: "2024-05-23",
    logoInitials: "IC",
    logoColor: "bg-slate-700",
    matchScore: 70,
    easyApply: false,
    externalUrl: "https://infracore.io/careers/devops",
    applicants: 34,
    recruiterName: "Robert Lee",
    recruiterTitle: "Technical Recruiter",
    promoted: false,
    activelyRecruiting: true,
    connectionsAtCompany: 3
  },
  {
    id: "7",
    title: "Junior Frontend Developer",
    company: "WebWorks",
    location: "Chicago, IL",
    type: "Full-time",
    workplaceType: "Hybrid",
    experience: "Entry Level",
    salary: "$70k – $90k",
    salaryMin: 70000,
    salaryMax: 90000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["HTML", "CSS", "JavaScript"],
    skillsRequired: ["HTML", "CSS", "JavaScript", "React Basics", "Git"],
    description: "Great opportunity for a junior developer to join a fast-paced agency building websites for modern brands. You'll learn from senior mentors and grow quickly.",
    requirements: ["Solid understanding of the DOM", "Familiarity with modern CSS (Flexbox/Grid)", "Eagerness to learn", "Basic JavaScript knowledge"],
    responsibilities: ["Build responsive web pages from design mockups", "Write clean, maintainable HTML, CSS, and JavaScript", "Participate in code reviews and pair programming sessions", "Help debug and fix cross-browser compatibility issues", "Contribute to internal tools and component libraries"],
    benefits: ["Mentorship program", "Health insurance", "Paid internships for conferences", "Team lunch Fridays", "Career growth path"],
    companyOverview: "WebWorks is a digital agency specializing in crafting stunning, high-performance websites for brands that want to make an impact. We're a close-knit team that values creativity and continuous learning.",
    companySize: "11–50 employees",
    companyIndustry: "Web Design Agency",
    companyFounded: "2020",
    postedAt: "2 weeks ago",
    postedDate: "2024-05-16",
    logoInitials: "WW",
    logoColor: "bg-indigo-600",
    matchScore: 88,
    easyApply: true,
    applicants: 12,
    promoted: false,
    activelyRecruiting: true,
    connectionsAtCompany: 1
  },
  {
    id: "8",
    title: "Principal Software Engineer",
    company: "NexusHealth",
    location: "Remote",
    type: "Full-time",
    workplaceType: "Remote",
    experience: "Executive",
    salary: "$180k – $220k",
    salaryMin: 180000,
    salaryMax: 220000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["Architecture", "Java", "Spring Boot"],
    skillsRequired: ["Java", "Spring Boot", "System Design", "Microservices", "Healthcare Compliance", "Team Leadership"],
    description: "Define the technical vision for our healthcare platform. You'll architect scalable solutions that handle sensitive medical data securely and mentor engineering teams.",
    requirements: ["10+ years engineering experience", "System architecture expertise", "Deep background in Java ecosystem", "Healthcare/FinTech compliance experience preferred"],
    responsibilities: ["Define and drive the overall technical architecture and strategy", "Lead cross-functional teams on critical platform initiatives", "Ensure security and compliance standards for healthcare data", "Establish engineering best practices and coding standards", "Present technical strategy to executive leadership"],
    benefits: ["Executive compensation package", "Significant equity grant", "Executive coach", "Premium health insurance", "Remote work stipend ($2,000)"],
    companyOverview: "NexusHealth is a healthcare technology company building the next generation of patient care platforms. Our mission is to improve healthcare outcomes through secure, intelligent technology that connects patients, providers, and data.",
    companySize: "501–1,000 employees",
    companyIndustry: "Health Tech",
    companyFounded: "2015",
    postedAt: "1 day ago",
    postedDate: "2024-05-29",
    logoInitials: "NH",
    logoColor: "bg-red-600",
    matchScore: 55,
    easyApply: true,
    applicants: 19,
    recruiterName: "Jennifer Walsh",
    recruiterTitle: "Executive Recruiter",
    promoted: true,
    activelyRecruiting: true,
    connectionsAtCompany: 0
  },
  {
    id: "9",
    title: "Freelance Copywriter",
    company: "WordSmith",
    location: "Remote",
    type: "Contract",
    workplaceType: "Remote",
    experience: "Mid Level",
    salary: "$40 – $60 / hr",
    salaryMin: 40,
    salaryMax: 60,
    salaryCurrency: "USD",
    salaryPeriod: "hour",
    tags: ["Copywriting", "Creative", "Ad Copy"],
    skillsRequired: ["Copywriting", "Creative Writing", "SEO Writing", "Email Marketing", "Brand Voice"],
    description: "Looking for a versatile freelance copywriter to help with ad campaigns, landing page copy, and email newsletters. This is a 6-month contract with possibility of extension.",
    requirements: ["Compelling portfolio", "Ability to adapt tone of voice", "Experience with conversion copywriting", "Self-starter mindset"],
    responsibilities: ["Write compelling ad copy for digital campaigns", "Craft landing page copy optimized for conversions", "Develop email newsletter content and subject lines", "Collaborate with designers on visual copy integration", "A/B test copy variations and report on performance"],
    benefits: ["Flexible hours", "Weekly payment", "Remote collaboration", "Portfolio development", "Potential for full-time conversion"],
    companyOverview: "WordSmith is a creative content agency that helps brands find their voice. We specialize in conversion-focused copywriting, content strategy, and brand storytelling that drives measurable results.",
    companySize: "11–50 employees",
    companyIndustry: "Content Agency",
    companyFounded: "2021",
    postedAt: "2 days ago",
    postedDate: "2024-05-28",
    logoInitials: "WS",
    logoColor: "bg-indigo-500",
    matchScore: 25,
    easyApply: true,
    applicants: 89,
    promoted: false,
    activelyRecruiting: false,
    connectionsAtCompany: 0
  },
  {
    id: "10",
    title: "HR Business Partner",
    company: "PeopleFirst",
    location: "Denver, CO",
    type: "Full-time",
    workplaceType: "On-site",
    experience: "Senior",
    salary: "$100k – $130k",
    salaryMin: 100000,
    salaryMax: 130000,
    salaryCurrency: "USD",
    salaryPeriod: "year",
    tags: ["HR", "Culture", "Recruiting"],
    skillsRequired: ["HR Management", "Talent Acquisition", "Employee Relations", "Performance Management", "SHRM Certification"],
    description: "Champion our company culture and oversee all HR functions including talent acquisition, employee relations, and performance management.",
    requirements: ["5+ years HR experience", "SHRM certification preferred", "Empathetic communication style", "Experience with HRIS systems"],
    responsibilities: ["Partner with leadership on organizational development initiatives", "Manage full-cycle talent acquisition and onboarding", "Develop and implement employee engagement programs", "Handle employee relations issues with discretion and fairness", "Ensure HR compliance with local, state, and federal regulations"],
    benefits: ["Comprehensive health coverage", "Employee wellness programs", "Professional development", "Volunteer time off", "Pet-friendly office"],
    companyOverview: "PeopleFirst is a people-centric organization dedicated to building healthy, productive workplaces. We believe that great companies are built on great teams, and our HR solutions help organizations attract, retain, and develop top talent.",
    companySize: "201–500 employees",
    companyIndustry: "Human Resources",
    companyFounded: "2017",
    postedAt: "4 days ago",
    postedDate: "2024-05-26",
    logoInitials: "PF",
    logoColor: "bg-teal-500",
    matchScore: 20,
    easyApply: false,
    externalUrl: "https://peoplefirst.co/careers/hr-bp",
    applicants: 211,
    recruiterName: "Laura Martinez",
    recruiterTitle: "People Operations",
    promoted: false,
    activelyRecruiting: true,
    connectionsAtCompany: 1
  }
];

type ExpandedJobSeed = readonly [
  company: string,
  title: string,
  industry: string,
  location: string,
  workplaceType: Job['workplaceType'],
  experience: Job['experience'],
  tags: readonly [string, string, string],
];

const EXPANDED_JOB_SEEDS: ExpandedJobSeed[] = [
  ['Lumen Systems', 'Platform Engineer', 'Cloud Communications', 'Seattle, WA', 'Hybrid', 'Senior', ['Kubernetes', 'Go', 'Observability']],
  ['Orbit Commerce', 'Product Analyst', 'E-commerce', 'Toronto, Canada', 'Remote', 'Mid Level', ['SQL', 'Funnels', 'Experimentation']],
  ['Northstar Labs', 'Accessibility Designer', 'Product Design', 'Portland, OR', 'Remote', 'Mid Level', ['Accessibility', 'Figma', 'Research']],
  ['Arc Studio', 'Brand Designer', 'Creative Services', 'Los Angeles, CA', 'Hybrid', 'Mid Level', ['Brand Systems', 'Figma', 'Art Direction']],
  ['WaveLab', 'Operations Designer', 'Logistics Technology', 'Singapore', 'Hybrid', 'Senior', ['Service Design', 'Operations', 'Prototyping']],
  ['BrightLedger', 'FinOps Analyst', 'Financial Technology', 'London, UK', 'Hybrid', 'Mid Level', ['FinOps', 'AWS', 'Cost Analytics']],
  ['Cedar Health', 'Clinical Product Manager', 'Health Technology', 'Boston, MA', 'Hybrid', 'Senior', ['Product Strategy', 'Healthcare', 'Analytics']],
  ['ParcelPilot', 'Logistics Data Engineer', 'Supply Chain Software', 'Chicago, IL', 'On-site', 'Mid Level', ['Python', 'Airflow', 'Snowflake']],
  ['NovaGrid', 'Renewable Energy Analyst', 'Clean Energy', 'Austin, TX', 'Hybrid', 'Entry Level', ['Energy Modeling', 'Excel', 'Data Visualization']],
  ['SignalNest', 'Customer Success Manager', 'B2B Software', 'Remote', 'Remote', 'Senior', ['Customer Success', 'SaaS', 'Retention']],
  ['HarborPay', 'Fraud Analyst', 'Payments', 'New York, NY', 'Hybrid', 'Mid Level', ['Fraud Detection', 'SQL', 'Risk']],
  ['PixelFoundry', 'Mobile Engineer', 'Mobile Products', 'Berlin, Germany', 'Remote', 'Mid Level', ['React Native', 'TypeScript', 'Mobile UX']],
  ['QuantumLeaf', 'Research Engineer', 'Applied Research', 'Zurich, Switzerland', 'On-site', 'Senior', ['Python', 'Algorithms', 'Prototyping']],
  ['MeadowWorks', 'Sustainability Manager', 'Environmental Services', 'Vancouver, Canada', 'Hybrid', 'Senior', ['ESG', 'Reporting', 'Program Management']],
  ['AtlasRoute', 'Solutions Architect', 'Enterprise Software', 'Dubai, UAE', 'Hybrid', 'Senior', ['Architecture', 'Cloud', 'Customer Discovery']],
  ['CopperCloud', 'Site Reliability Engineer', 'Cloud Infrastructure', 'Denver, CO', 'Remote', 'Senior', ['SRE', 'Terraform', 'Incident Response']],
  ['CivicData', 'Business Intelligence Developer', 'Public Data', 'Washington, DC', 'Hybrid', 'Mid Level', ['Power BI', 'SQL', 'Data Modeling']],
  ['FrameShift', 'Motion Designer', 'Digital Media', 'Paris, France', 'Remote', 'Mid Level', ['Motion Design', 'After Effects', 'Storytelling']],
  ['KeenSearch', 'SEO Strategist', 'Marketing Technology', 'Manchester, UK', 'Remote', 'Mid Level', ['SEO', 'Content Strategy', 'Analytics']],
  ['RelayWorks', 'Integration Engineer', 'Workflow Automation', 'Dublin, Ireland', 'Hybrid', 'Mid Level', ['APIs', 'Node.js', 'Integrations']],
  ['BluePeak', 'Security Engineer', 'Cybersecurity', 'San Diego, CA', 'On-site', 'Senior', ['Cloud Security', 'SIEM', 'Threat Modeling']],
  ['TerraFoods', 'Supply Chain Analyst', 'Food Technology', 'Amsterdam, Netherlands', 'Hybrid', 'Entry Level', ['Supply Chain', 'Forecasting', 'Excel']],
  ['MindSpring', 'Learning Designer', 'Education Technology', 'Remote', 'Remote', 'Mid Level', ['Instructional Design', 'LMS', 'Facilitation']],
  ['ClearVoice', 'Content Strategist', 'Content Technology', 'Atlanta, GA', 'Remote', 'Senior', ['Content Strategy', 'Research', 'Editorial']],
  ['VectorForge', 'Machine Learning Engineer', 'Artificial Intelligence', 'San Jose, CA', 'Hybrid', 'Senior', ['Python', 'PyTorch', 'MLOps']],
  ['OpenHarbor', 'Community Manager', 'Developer Platforms', 'Remote', 'Remote', 'Mid Level', ['Community', 'Events', 'Developer Relations']],
  ['LanternAI', 'AI Product Manager', 'Artificial Intelligence', 'San Francisco, CA', 'Hybrid', 'Senior', ['AI Products', 'Roadmaps', 'Evaluation']],
  ['Mono Engineering', 'TypeScript Engineer', 'Developer Tools', 'Helsinki, Finland', 'Remote', 'Mid Level', ['TypeScript', 'Node.js', 'Developer Experience']],
  ['Greenhouse Network', 'Climate Program Lead', 'Climate Technology', 'Copenhagen, Denmark', 'Hybrid', 'Senior', ['Climate Programs', 'Partnerships', 'Impact Measurement']],
  ['BeaconCRM', 'Revenue Operations Manager', 'Sales Technology', 'New York, NY', 'Hybrid', 'Senior', ['Revenue Operations', 'CRM', 'Forecasting']],
  ['Alpine Robotics', 'Robotics Software Engineer', 'Robotics', 'Munich, Germany', 'On-site', 'Senior', ['C++', 'ROS', 'Computer Vision']],
  ['OceanByte', 'QA Automation Engineer', 'Software Quality', 'Lisbon, Portugal', 'Remote', 'Mid Level', ['Playwright', 'Automation', 'JavaScript']],
  ['SummitLegal', 'Legal Operations Analyst', 'Legal Technology', 'London, UK', 'Hybrid', 'Mid Level', ['Legal Operations', 'Process Design', 'Analytics']],
  ['HelioBank', 'Mobile Product Designer', 'Digital Banking', 'Madrid, Spain', 'Hybrid', 'Mid Level', ['Mobile Design', 'Figma', 'FinTech']],
  ['FreightFox', 'Backend Engineer', 'Freight Technology', 'Memphis, TN', 'Remote', 'Mid Level', ['Go', 'PostgreSQL', 'Distributed Systems']],
  ['KindredCare', 'UX Researcher', 'Care Technology', 'Melbourne, Australia', 'Hybrid', 'Mid Level', ['UX Research', 'Interviews', 'Synthesis']],
  ['PrismMedia', 'Growth Analyst', 'Media Technology', 'Los Angeles, CA', 'Hybrid', 'Entry Level', ['Growth Analytics', 'SQL', 'A/B Testing']],
  ['SolarStack', 'Cloud Engineer', 'Energy Software', 'Phoenix, AZ', 'Remote', 'Senior', ['AWS', 'Terraform', 'Kubernetes']],
  ['MapleHR', 'People Analytics Specialist', 'Human Resources Technology', 'Montreal, Canada', 'Hybrid', 'Mid Level', ['People Analytics', 'SQL', 'Tableau']],
  ['Skylane Aerospace', 'Aerospace Systems Engineer', 'Aerospace', 'Toulouse, France', 'On-site', 'Senior', ['Systems Engineering', 'Simulation', 'Safety']],
];

const LOGO_COLORS = ['bg-blue-600', 'bg-violet-600', 'bg-emerald-600', 'bg-cyan-600', 'bg-rose-600', 'bg-amber-600', 'bg-indigo-600', 'bg-teal-600'];
const COMPANY_SIZES = ['11–50 employees', '51–200 employees', '201–500 employees', '501–1,000 employees'];

const EXPANDED_JOBS: Job[] = EXPANDED_JOB_SEEDS.map((seed, index) => {
  const [company, title, industry, location, workplaceType, experience, seedTags] = seed;
  const tags = [...seedTags];
  const salaryMin = 78_000 + (index % 9) * 9_000;
  const salaryMax = salaryMin + 28_000;
  const initials = company.split(/\s+/).map((word) => word[0]).join('').slice(0, 2).toUpperCase();

  return {
    id: String(index + 11),
    title,
    company,
    location,
    type: index % 11 === 0 ? 'Contract' : 'Full-time',
    workplaceType,
    experience,
    salary: `$${Math.round(salaryMin / 1_000)}k – $${Math.round(salaryMax / 1_000)}k`,
    salaryMin,
    salaryMax,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    tags,
    skillsRequired: [...tags, 'Cross-functional Collaboration', 'Clear Communication'],
    description: `${company} is hiring a ${title} to own meaningful work across its ${industry.toLowerCase()} products and services. You will turn customer and business needs into reliable outcomes, collaborate with a multidisciplinary team, and improve how the organization measures quality and impact.`,
    requirements: [
      `Demonstrated experience relevant to a ${experience.toLowerCase()} ${title} role`,
      `Hands-on capability with ${tags[0]} and ${tags[1]}`,
      'Clear written and verbal communication across technical and non-technical teams',
      'Evidence of shipping work, improving a process, or influencing a measurable outcome',
      'Comfort working through ambiguity and documenting important decisions',
    ],
    responsibilities: [
      `Own planning and delivery for priority ${title.toLowerCase()} initiatives`,
      `Apply ${tags[0]} and ${tags[1]} to solve practical customer problems`,
      'Partner with product, design, engineering, operations, and commercial stakeholders',
      'Define success measures, review results, and communicate progress clearly',
      'Improve team standards, documentation, and repeatable ways of working',
    ],
    benefits: ['Comprehensive health coverage', 'Flexible paid time off', 'Learning and development budget', `${workplaceType} work support`, 'Inclusive parental leave'],
    companyOverview: `${company} builds modern solutions in ${industry.toLowerCase()}. Its teams combine customer insight, responsible technology, and measurable delivery to help organizations work more effectively.`,
    companySize: COMPANY_SIZES[index % COMPANY_SIZES.length],
    companyIndustry: industry,
    companyFounded: String(2008 + (index % 15)),
    postedAt: `${index % 6 + 1} day${index % 6 === 0 ? '' : 's'} ago`,
    postedDate: `2026-07-${String(26 - (index % 20)).padStart(2, '0')}`,
    logoInitials: initials,
    logoColor: LOGO_COLORS[index % LOGO_COLORS.length],
    matchScore: 45 + (index * 7) % 51,
    easyApply: index % 4 !== 0,
    applicants: 14 + (index * 17) % 190,
    recruiterName: `${['Maya', 'Daniel', 'Priya', 'Lucas', 'Sofia'][index % 5]} ${['Chen', 'Okafor', 'Patel', 'Martin', 'Garcia'][index % 5]}`,
    recruiterTitle: 'Talent Partner',
    promoted: index % 5 === 0,
    activelyRecruiting: index % 6 !== 0,
    connectionsAtCompany: index % 7,
  };
});

export const MOCK_JOBS: Job[] = [...CORE_JOBS, ...EXPANDED_JOBS];
